language: node_js
node_js:
    - stable

branches:
    only:
        - develop

before_install:
    - npm install -g grunt-cli bower

install:
    - npm install
    - bower install

script:
    - grunt package

after_success:
    - git config user.name "Travis CI"
    - git config user.email "rrdelaney@outlook.com"
    - git remote add deploy https://${GITHUB_TOKEN}@github.com/rrdelaney/rrdelaney.github.io.git
    - git checkout --orphan masterStaging
    - git reset -- .
    - git add -f index.html
    - git add CNAME
    - git commit -m "Travis CI Build"
    - git push --force --quiet -u deploy masterStaging:master
