language: node_js

node_js:
    - stable

sudo: false

before_install:
    - npm install -g grunt-cli bower

install:
    - npm install
    - bower install

script:
    - grunt package

after_success:
    - grunt deploy
