language: node_js
node_js:
    - stable

branches:
    only:
        - develop

before_install:
    - npm install -g grunt-cli bower
    - npm install
    - bower install

script:
    - grunt package

after_success:
    - git config user.name "Travis CI"
    - git config user.email "rrdelaney@outlook.com"
    - git add index.html
    - git commit -m "Travis CI Build"
    - git push --force --quiet "https://${GIHUB_TOKEN}@github.com/rrdelaney/rrdelaney.github.io"
