# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Framework"
license = "MIT"
licenselink = "https://github.com/rrdelaney/rrdelaney.github.io/blob/master/themes/framework/LICENSE.md"
description = ""
homepage = "http://rdel.io/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Ryan Delaney"
  homepage = "http://rdel.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
