#!/bin/sh
cd target/public_html
git init
git config user.name "Travis CI"
git config user.email "rrdelaney@outlook.com"
git remote add deploy https://github.com/rrdelaney/rrdelaney.github.io.git
git add --all
git commit -m "Travis CI Build"
git push --force --quiet -u deploy master
